import Head from "next/head";
// import Link from "next/link";
// import Image from 'next/image';
// import logoIpsum from '../../public/logoipsum.svg'
// import { lusitana } from '../ui/fonts';
// import { ArrowRightIcon } from '@heroicons/react/24/outline';
// import {  useAuth } from "@clerk/nextjs";
// import { Suspense } from "react";
// import { api } from "~/utils/api";
import Layout from "../../components/layout";
import { lusitana } from "../ui/fonts";



export default function Dashboard() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  // const user = useAuth()

  return (
    <>
      <Head>
        <title>DealFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout>  
            <main>
            <h1 className={`${lusitana.className} mb-4 text-xl md:text-2xl`}>
        Dashboard
      </h1>
              </main>

              </Layout>
    </>
  );
}




// import CardWrapper  from '@/app/ui/dashboard/cards';
// import RevenueChart from '@/app/ui/dashboard/revenue-chart';
// import LatestInvoices from '@/app/ui/dashboard/latest-invoices';

// import { fetchLatestInvoices, fetchCardData } from '@/app/lib/data';
// import { Suspense } from 'react';
// import { LatestInvoicesSkeleton, RevenueChartSkeleton, CardsSkeleton } from '@/app/ui/skeletons';
 
// export default async function Page() {
//   const latestInvoices = await fetchLatestInvoices();
//   const {
//     numberOfInvoices,
//     numberOfCustomers,
//     totalPaidInvoices,
//     totalPendingInvoices,
//   } = await fetchCardData();
 
//   return (
//     <main>
//       <h1 className={`${lusitana.className} mb-4 text-xl md:text-2xl`}>
//         Dashboard
//       </h1>
//       <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
//         <Suspense fallback={<CardsSkeleton />}>
//           <CardWrapper />
//         </Suspense>
//       </div>
//       <div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-4 lg:grid-cols-8">
//         <Suspense fallback={<LatestInvoicesSkeleton />}>
//           <LatestInvoices />
//         </Suspense>
//         <Suspense fallback={<RevenueChartSkeleton />}>
//           <RevenueChart />
//         </Suspense>

//         {/* <LatestInvoices latestInvoices={latestInvoices} /> */}
//       </div>
//     </main>
//   );
// }
