import Head from "next/head";
import Link from "next/link";
import Image from 'next/image';
import logoIpsum from '../../public/logoipsum.svg'
import { lusitana } from './ui/fonts';
import { ArrowRightIcon } from '@heroicons/react/24/outline';
import { SignInButton, useAuth } from "@clerk/nextjs";

import { api } from "~/utils/api";



export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const user = useAuth()

  return (
    <>
      <Head>
        <title>DealFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className="flex min-h-screen flex-col p-6">
      <div className="flex h-20 shrink-0 items-end rounded-lg bg-blue-500 p-4 md:h-52">
        <div className="w-32 text-white md:w-40">
              {/* <AcmeLogo /> */}
              <h1 className={`${lusitana.className} mb-4 text-4xl md:text-4xl`}>DealFlow</h1>
        </div>
      </div>
      <div className="mt-4 flex grow flex-col gap-4 md:flex-row">
        <div className="flex flex-col justify-center gap-6 rounded-lg bg-gray-50 px-6 py-10 md:w-2/5 md:px-20">
          <Image
            src={logoIpsum}
            alt="DealFlow Logo"
            height={80}
            width={80}
            />
          <p className={`text-xl text-gray-800 md:text-3xl md:leading-normal`}>
            <strong>Welcome to DealFlow.</strong> All-in-one CRM Software for {' '}
            the Insurance & Finance industries.
            </p>
            
            {user.isSignedIn ? 
              (
                <div>
                  <Link
            href="/dashboard"
            className="flex items-center gap-5 self-start rounded-lg bg-blue-500 px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-blue-400 md:text-base"
          >
            <span>Dashboard</span> <ArrowRightIcon className="w-5 md:w-6" />
                  </Link>
                </div>

              ) : (
              <div className="flex flex-nowrap gap-8">
                  <Link
            href="/sign-in"
                    className="flex border-solid border-2 border-blue-500 items-center gap-5 self-start rounded-lg bg-blue-500
             px-6 py-3  font-medium text-white transition-colors md:text-base hover:text-blue-500 hover:bg-white 
             hover:border-solid hover:border-2 hover:border-blue-500"
          >
            <span>Login</span> <ArrowRightIcon className="w-5 md:w-6" />
            
                  </Link>
                <Link
                    href="/sign-up"
                 
                    className="border-solid border-2 border-blue-500 hover:text-white rounded-lg
             bg-white w-auto px-8 py-3 font-medium text-blue-500 transition-colors hover:bg-blue-500 md:text-base "
          > <p className="whitespace-nowrap">Sign Up</p> 
                  </Link>
                </div>
                  
              )}
             </div>
          {/* <Link
            href="/dashboard"
            className="flex items-center gap-5 self-start rounded-lg bg-blue-500 px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-blue-400 md:text-base"
          >
            <span>Log in</span> <ArrowRightIcon className="w-5 md:w-6" />
          </Link> */}
       
        <div className="flex items-center justify-center p-6 md:w-3/5 md:px-28 md:py-12">
          {/* Add Hero Images Here */}
        {/* <Image
          src="/hero-desktop.png"
          width={1000}
          height={760}
          className="hidden md:block"
          alt="Screenshots of the dashboard project showing desktop version"
        />
        <Image
          src="/hero-mobile.png"
          width={560}
          height={620}
          className="block md:hidden"
          alt="Screenshot of the dashboard project showing mobile version"
        /> */}
        </div>
      </div>
    </main>
    </>
  );
}
